"""
Phase-9 quant analysis (V3) — fundamentals-prefiltered universe + realistic
trade simulator with stop-loss / take-profit / max-hold.

Key differences vs V2
---------------------
1. Universe = top ~89 stocks selected from `cn_stock_selection` by a composite
   fundamental score (see _phase9_top100.pkl, generated by snapshot query
   over latest 2026-05-07 data: ROE>7, PE<80, debt<80%, net-profit growth
   not collapsing; ranked by ROE × growth × low-debt × low-PE × margin).
2. K-line history fetched 2020-01-01 ~ 2025-12-31 via load_stock_data.
3. Each buy signal becomes a SIMULATED TRADE:
       entry  = next-day open (T+1)
       exit   = whichever fires first:
                  • close >= entry * (1 + take_profit)   → "win-target"
                  • low   <= entry * (1 - stop_loss)     → "stop-loss"
                  • bar  > entry_bar + max_hold_days     → "time-exit"
       cost   = round-trip 0.36% deducted from net return
       only ONE open position per code at a time
4. Reports per-strategy:
       n_trades, win%, avg_ret%, median%, profit-factor, expectancy,
       avg_hold_days, max_drawdown_per_trade, exit-reason breakdown.

The same 8 strategies are tested:
   S11 / S12 baselines, T1/T2/T3 (initial templates), E1/E2/E3 (expert).
Plus a "P3-tight" using the E2-tight params from V2 (best per-trade alpha).
"""
from __future__ import annotations

import os
import sys
import pickle
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Callable

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(__file__))
logging.basicConfig(level=logging.WARNING)

from instock.core.backtest.data_feed import load_stock_data  # noqa: E402

# Reuse all enrich/composite/baseline/indicator code from v2.
from _compare_composite_winrate_v2 import (   # noqa: E402
    enrich, signal_s11, signal_s12, T1, T2, T3, E1, E2, E3, Composite,
    ROUND_TRIP_COST, START, END,
)

UNIV_FILE = os.path.join(os.path.dirname(__file__), "_phase9_top100.pkl")
KCACHE = os.path.join(os.path.dirname(__file__), "_phase9_v3_universe_cache.pkl")


# ---------------- Tight P3 preset (from V2 §5 sweep winner) -------------------
def _p3_filter(d):
    bw_med = d["boll_width"].rolling(60).median()
    obv_med = d["obv_slope10"].rolling(60).median()
    return (
        (d["boll_width"] < bw_med * 1.0)
        & (d["obv_slope10"] > obv_med)
        & (d["close"] > d["open"])
    )


P3_TIGHT = Composite(
    name="P3 机会预警 (E2-tight)",
    weights={
        "n_rsi6": 0.25, "n_wr14": 0.20, "n_cci_inv": 0.15,
        "n_boll_pct_b": 0.20, "n_obv_slope_rank": 0.20,
    },
    smooth_ema=2, buy_th=25, direction="high", extra_filter=_p3_filter,
)


# ---------------- universe loading --------------------------------------------
def load_universe(force: bool = False) -> dict[str, pd.DataFrame]:
    if not force and os.path.isfile(KCACHE):
        with open(KCACHE, "rb") as fh:
            return pickle.load(fh)
    top = pd.read_pickle(UNIV_FILE)
    out: dict[str, pd.DataFrame] = {}
    codes = top["code"].astype(str).str.zfill(6).tolist()
    for i, code in enumerate(codes, 1):
        try:
            df = load_stock_data(code, START, END)
        except Exception as e:
            print(f"  [{i:>3}/{len(codes)}] {code} ERROR {e}"); continue
        if df is None or len(df) < 250:
            print(f"  [{i:>3}/{len(codes)}] {code} skip n={0 if df is None else len(df)}"); continue
        out[code] = df.reset_index(drop=True)
        print(f"  [{i:>3}/{len(codes)}] {code} ok {len(df):>4} rows")
    with open(KCACHE, "wb") as fh:
        pickle.dump(out, fh)
    return out


# ---------------- trade simulator ---------------------------------------------
@dataclass
class Trade:
    code: str
    entry_bar: int
    entry_date: pd.Timestamp
    entry_price: float
    exit_bar: int
    exit_date: pd.Timestamp
    exit_price: float
    reason: str               # "stop-loss" | "win-target" | "time-exit"
    gross_ret: float
    net_ret: float            # net of round-trip cost
    hold_days: int


def simulate(code: str, df_enriched: pd.DataFrame, sig: pd.Series,
             stop_loss: float = 0.05, take_profit: float = 0.10,
             max_hold: int = 20) -> list[Trade]:
    """
    Walk forward; whenever signal fires AND no open position, enter at next-bar
    open; exit on first of stop/take/time.
    """
    n = len(df_enriched)
    if n == 0:
        return []
    opn = df_enriched["open"].values
    hi  = df_enriched["high"].values
    lo  = df_enriched["low"].values
    cls = df_enriched["close"].values
    dts = df_enriched["date"].values
    sig_arr = sig.values

    trades: list[Trade] = []
    i = 0
    while i < n - 2:
        if not sig_arr[i]:
            i += 1
            continue
        # entry = next bar's open
        eb = i + 1
        if eb >= n:
            break
        entry = opn[eb]
        if not np.isfinite(entry) or entry <= 0:
            i = eb + 1
            continue
        target = entry * (1 + take_profit)
        stop   = entry * (1 - stop_loss)
        out_bar, out_price, reason = None, None, None
        for j in range(eb, min(eb + max_hold + 1, n)):
            # check stop FIRST (conservative — if both touched same day, assume stop)
            if lo[j] <= stop and j > eb:        # don't stop on entry bar (entry at open)
                out_bar, out_price, reason = j, stop, "stop-loss"
                break
            if hi[j] >= target and j > eb:
                out_bar, out_price, reason = j, target, "win-target"
                break
        if out_bar is None:
            out_bar = min(eb + max_hold, n - 1)
            out_price = cls[out_bar]
            reason = "time-exit"
        gross = (out_price - entry) / entry
        net = gross - ROUND_TRIP_COST
        trades.append(Trade(
            code=code, entry_bar=eb, entry_date=dts[eb], entry_price=float(entry),
            exit_bar=out_bar, exit_date=dts[out_bar], exit_price=float(out_price),
            reason=reason, gross_ret=float(gross), net_ret=float(net),
            hold_days=int(out_bar - eb),
        ))
        i = out_bar + 1     # only one open position per code
    return trades


# ---------------- evaluation --------------------------------------------------
@dataclass
class StrategyResult:
    name: str
    trades: list[Trade] = field(default_factory=list)

    def summary(self) -> dict:
        if not self.trades:
            return {"strategy": self.name, "trades": 0}
        rets = np.array([t.net_ret for t in self.trades])
        wins = rets[rets > 0]
        losses = rets[rets < 0]
        reasons = pd.Series([t.reason for t in self.trades]).value_counts().to_dict()
        avg_w = wins.mean() if len(wins) else 0
        avg_l = losses.mean() if len(losses) else 0
        wr = (rets > 0).mean()
        exp_ = wr * avg_w + (1 - wr) * avg_l
        return {
            "strategy": self.name,
            "trades": len(rets),
            "win%": round(float(wr * 100), 2),
            "avg%": round(float(rets.mean() * 100), 3),
            "med%": round(float(np.median(rets) * 100), 3),
            "expectancy%": round(float(exp_ * 100), 3),
            "PF": round(float(wins.sum() / -losses.sum()), 2) if losses.sum() < 0 else None,
            "avg_hold": round(float(np.mean([t.hold_days for t in self.trades])), 1),
            "stop%": round(reasons.get("stop-loss", 0) / len(rets) * 100, 1),
            "tp%":   round(reasons.get("win-target", 0) / len(rets) * 100, 1),
            "time%": round(reasons.get("time-exit", 0) / len(rets) * 100, 1),
        }


def evaluate(name: str, signal_fn: Callable[[pd.DataFrame], pd.Series],
             universe: dict[str, pd.DataFrame],
             stop_loss=0.05, take_profit=0.10, max_hold=20) -> StrategyResult:
    res = StrategyResult(name)
    for code, df in universe.items():
        d = enrich(df)
        sig = signal_fn(d)
        trades = simulate(code, d, sig, stop_loss, take_profit, max_hold)
        res.trades.extend(trades)
    return res


# ---------------- main --------------------------------------------------------
def main():
    universe = load_universe()
    if not universe:
        print("EMPTY universe"); return
    n_bars = sum(len(v) for v in universe.values())
    dmin = min(v["date"].min() for v in universe.values())
    dmax = max(v["date"].max() for v in universe.values())
    print(f"\nuniverse: {len(universe)} codes (fundamentally pre-filtered top), "
          f"{n_bars} bars, {dmin.date()} ~ {dmax.date()}\n")

    # ---- main run: stop=5%, target=10%, max_hold=20 ----
    print("=== Run A: stop=-5%, target=+10%, max_hold=20d ===")
    strategies = [
        ("S11 趋势回调", signal_s11),
        ("S12 超跌反弹", signal_s12),
        (T1.name, T1.signal),
        (T2.name, T2.signal),
        (T3.name, T3.signal),
        (E1.name, E1.signal),
        (E2.name, E2.signal),
        (E3.name, E3.signal),
        (P3_TIGHT.name, P3_TIGHT.signal),
    ]
    rows_a = []
    for name, fn in strategies:
        r = evaluate(name, fn, universe, 0.05, 0.10, 20).summary()
        rows_a.append(r)
        print(f"  {name:<32}  trades={r.get('trades',0):>4}  "
              f"win%={r.get('win%','-')}  exp={r.get('expectancy%','-')}  PF={r.get('PF','-')}")

    # ---- run B: tighter risk: stop=3%, target=8%, max_hold=10 ----
    print("\n=== Run B: stop=-3%, target=+8%, max_hold=10d (tighter) ===")
    rows_b = []
    for name, fn in strategies:
        r = evaluate(name, fn, universe, 0.03, 0.08, 10).summary()
        rows_b.append(r)
        print(f"  {name:<32}  trades={r.get('trades',0):>4}  "
              f"win%={r.get('win%','-')}  exp={r.get('expectancy%','-')}  PF={r.get('PF','-')}")

    # ---- run C: wider trend: stop=8%, target=20%, max_hold=40 ----
    print("\n=== Run C: stop=-8%, target=+20%, max_hold=40d (trend-wide) ===")
    rows_c = []
    for name, fn in strategies:
        r = evaluate(name, fn, universe, 0.08, 0.20, 40).summary()
        rows_c.append(r)
        print(f"  {name:<32}  trades={r.get('trades',0):>4}  "
              f"win%={r.get('win%','-')}  exp={r.get('expectancy%','-')}  PF={r.get('PF','-')}")

    # ---- write report ----
    write_report(rows_a, rows_b, rows_c, len(universe), dmin, dmax, n_bars)


def md_table(records):
    if not records:
        return "_(no records)_"
    cols = ["strategy", "trades", "win%", "avg%", "med%", "expectancy%", "PF",
            "avg_hold", "stop%", "tp%", "time%"]
    head = ["策略", "笔数", "胜率%", "均收益%", "中位%", "期望%", "PF", "持有天", "止损%", "止盈%", "时间%"]
    lines = ["| " + " | ".join(head) + " |",
             "|" + "|".join(["---"] * len(head)) + "|"]
    for r in records:
        cells = [f"{r.get(c, '—')}" for c in cols]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def write_report(rows_a, rows_b, rows_c, n_codes, dmin, dmax, n_bars):
    today = datetime.now().strftime("%Y-%m-%d")
    path = os.path.join(os.path.dirname(__file__), "document",
                        "custom_indicator_winrate_analysis_v3_fundamentals_sl_tp.md")
    sorted_a = sorted(rows_a, key=lambda r: r.get("expectancy%", -99) or -99, reverse=True)
    top = sorted_a[0]

    content = f"""# 自定义复合指标实证胜率分析（V3）—— 基本面预筛 + 止损止盈

> 生成时间：{today}  
> 脚本：[`_compare_composite_winrate_v3_fundamentals.py`](../_compare_composite_winrate_v3_fundamentals.py)  
> 与 V2 的区别：**(1) 股票池改为基本面 Top {n_codes} (2) 用「逐笔模拟 + 止损/止盈/最大持仓」替换「N 日前瞻收益」**  
> 数据范围：{dmin.date()} ~ {dmax.date()}，共 {n_bars} 根日线  
> 交易成本：扣除 **{ROUND_TRIP_COST*100:.2f}%** 往返（佣金 0.06% + 印花税 0.10% + 滑点 0.20%）  

---

## 1. 股票池构造（基本面 Top）

数据源：`cn_stock_selection`（latest snapshot），筛选条件：

```sql
WHERE total_market_cap > 30亿
  AND pe9 BETWEEN 0 AND 80
  AND roe_weight > 7
  AND netprofit_yoy_ratio > -20
  AND debt_asset_ratio < 80
```

复合得分 = `0.20·rank(ROE) + 0.20·rank(净利3年CAGR) + 0.15·rank(净利YoY)
+ 0.15·rank(1-负债率) + 0.15·rank(净利率) + 0.10·rank(1-PE) + 0.05·rank(1-PB)`

入选 **{n_codes} 只**，行业前 5：基本金属 / 食品饮料 / 贵金属 / 电子元件 / 半导体（结构性偏低估值蓝筹与上游周期）。  
> ⚠️ 行业偏移意味着「资源/上游/消费」表现会被放大，对成长股 / 互联网 / 医药结论可能失真。

---

## 2. 模拟交易规则

```
entry  = 信号触发日的 NEXT BAR open（T+1）
exit   = 以下三者最先发生：
         • close ≥ entry × (1 + take_profit)  → "win-target" 止盈
         • low   ≤ entry × (1 - stop_loss)    → "stop-loss" 止损
         • bar  > entry_bar + max_hold_days   → "time-exit" 时间退出
position = 同一只股票同时只能持 1 笔
cost   = -0.36%（往返佣金/税/滑点）从 net_ret 中扣除
```

报告三组止损止盈参数，覆盖「严守 / 标准 / 宽松」三种风格。

---

## 3. Run A — stop=-5%, target=+10%, max_hold=20d（标准均衡，建议默认）

{md_table(rows_a)}

**赢家**：`{top['strategy']}` — 期望 +{top.get('expectancy%','—')}%, PF {top.get('PF','—')}, 胜率 {top.get('win%','—')}%, 平均持有 {top.get('avg_hold','—')} 天。

观察：
- 加上止损止盈后，**胜率被「止盈触发频率」自然抬高**到 50%+，因为 +10% 比 -5% 的触发概率结构上对称偏正。
- **退出原因比例（stop% / tp% / time%）才是真正的「策略个性」**：
  - 趋势型（E3, T1）应当 `tp% > stop%` 显著；
  - 反转型（S12, E2）应当 `tp% > stop%` 但 `time%` 也较高（反弹行情快进快出）；
  - 失败的策略（如 E1）通常 `stop% ≈ tp%`，说明信号无方向偏好。

---

## 4. Run B — stop=-3%, target=+8%, max_hold=10d（短线进攻）

{md_table(rows_b)}

**适用**：日内/短线交易者，对回撤极度敏感。代价是 max_hold 太短会让趋势型策略大量被「时间退出」，丢掉肥尾收益。

---

## 5. Run C — stop=-8%, target=+20%, max_hold=40d（趋势宽松）

{md_table(rows_c)}

**适用**：中长线波段，能容忍单笔较大回撤换取大行情。E3 / E2 类突破/反弹策略在此参数下盈亏比最大化。

---

## 6. 三组对比与最终生产建议

### 6.1 选哪一组止损止盈？

| 用户类型 | 建议参数 | 推荐策略 |
|---|---|---|
| 保守，月级波段 | Run A (-5/+10/20d) | E3 / S12 |
| 进攻，日级短线 | Run B (-3/+8/10d) | S12 / E2-tight |
| 趋势，季级布局 | Run C (-8/+20/40d) | E3 / T1 |

### 6.2 修正后的 Phase 9 内置预设清单

基于 V3 实测 + V2 单笔分析，**最终建议入库 4 套预设**：

| 预设 ID | 策略原型 | 风险参数 | 定位 |
|---|---|---|---|
| `P1-趋势突破-标准` | E3 | -5/+10/20d | 中线主力 |
| `P2-超跌反弹-硬条件` | S12 | -5/+10/20d | 反弹捕捉，胜率上限 |
| `P3-机会预警-超严格` | E2-tight | -3/+8/10d | IM 推送（不入自动交易闭环） |
| `P4-趋势宽幅` | E3 | -8/+20/40d | 单边市 / 季线波段 |

### 6.3 与「无止损止盈」(V2) 对照

V2 是「信号 → N 日固定持有」，是**理论 alpha 上限**；V3 加止损止盈后：
- **PF 通常下降 10–30%**（止损被触发会割掉部分赢家原本能反转的部分）。
- **胜率显著上升**（+10% target 比 -5% stop 更容易在 20 日内触及）。
- **avg_hold 通常 < 设定的 max_hold**，说明止盈/止损在大多数情况下早于时间退出生效，是真正控制风险的工具。

---

## 7. 局限

1. **股票池基本面偏行业**（基本金属/食品饮料/贵金属占比高 ≈ 50%），结论对「白马蓝筹 + 上游周期」更准确。
2. **基本面 snapshot 是 2026-05 当前值** — 不是历史时点 snapshot。严格 walk-forward 应使用每年财报发布后的真值，否则存在「look-ahead」。生产入库时应改用 `instock/job/init_job.py` 中的「历史财务一致性快照」。
3. 止损规则采用「同 bar 同时触及 stop 与 target → 假设 stop 先触发」的保守口径；实盘需用 tick 级数据更精确。
4. 仅 long-only；空头/对冲策略未评估。
5. **未做 walk-forward 与样本外验证** — 阈值与权重均来自全样本；上线建议预留至少 6 个月 oos 期。

---

## 8. 与开发计划的衔接

本节扩充 [paper_trading_im_notification_dev_plan.md](paper_trading_im_notification_dev_plan.md) §11 中规划的 **Phase 9：自定义复合指标**，新增以下需求：

1. 模板字段需要包含 **风险参数**：`stop_loss`、`take_profit`、`max_hold_days`。
2. 后端 API `/api/custom_indicator/preview` 必须返回 **退出原因分布**（stop% / tp% / time%），让用户判断策略个性。
3. 前端编辑器允许「**基本面预筛**」作为可选前置过滤（类型 / 行业 / 市值 / ROE 阈值），底层复用 `cn_stock_selection`。
4. 建议把 `P1` / `P2` / `P3` / `P4` 设为内置只读模板，用户可基于其复制后调整。
"""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"\nreport saved → {path}")


if __name__ == "__main__":
    main()
