#!/bin/bash

# 获取脚本所在目录，计算项目根目录
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PROJECT_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)

export PYTHONIOENCODING=utf-8
export LANG=zh_CN.UTF-8
export PYTHONPATH=$PROJECT_ROOT
export LC_CTYPE=zh_CN.UTF-8

python3 $PROJECT_ROOT/instock/job/basic_data_daily_job.py

#mkdir -p $PROJECT_ROOT/instock/log
#DATE=`date +%Y-%m-%d:%H:%M:%S`
#echo $DATE >> $PROJECT_ROOT/instock/log/hourly.log